apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: default
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: ":80"
      websecure:
        address: ":443"

    certificatesResolvers:
      letsencrypt:
        acme:
          email: alain@tanoh.co
          storage: acme.json
          httpChallenge:
            entryPoint: web
    
    providers:
      kubernetesIngress: {}
